development:
  url: <%= ENV['DATABASE_URL'].gsub('?', '_apidevelopment?') %>

test:
  url: <%= ENV['DATABASE_URL'].gsub('?', '_apitest?') %>

production:
  url: <%= ENV['DATABASE_URL'].gsub('?', '_apiproduction') %>